services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - lancedb-data:/data/lancedb
    environment:
      - API_KEY=${API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-turbo}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - LANCEDB_URI=/data/lancedb
    restart: unless-stopped

volumes:
  lancedb-data:
